spring:
  application:
    name: bidan-report
  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by maven when building the JAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: #spring.profiles.active#
    group:
      dev:
        - dev
  jpa:
    open-in-view: false
    properties:
      hibernate.default_schema: sid_bidan
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.batch_versioned_data: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: none
  messages:
    basename: i18n/messages

server:
  port: 8081

# client-id and client-secret retrieved from
# https://docs.qontak.com/docs/omnichannel-hub/ZG9jOjE1MzEwMzc4-authentication#how-to-get-token
qontak:
  whats-app:
    base-url: https://chat-service.qontak.com
    client-id: RRrn6uIxalR_QaHFlcKOqbjHMG63elEdPTair9B9YdY
    client-secret: Sa8IGIh_HpVK1ZLAF0iFf7jU760osaUNV659pBIZR00
    api-path-broadcast-direct: /api/open/v1/broadcasts/whatsapp/direct
    api-path-authentication: /oauth/token

scheduling:
  enabled: true
  intro-message:
    fixed-rate-in-ms: 300000 # 5 minutes
    initial-delay-in-ms: 60000 # 1 minute
  visit-reminder:
    cron: "0 30 18 * * ?" # At 06:30 PM
    zone: Asia/Jakarta
  pregnancy-gap:
    fixed-rate-in-ms: 300000 # 5 minutes
    initial-delay-in-ms: 60000 # 1 minute
